# Docker Compose 配置 for FinTranzo
# 支持完整的開發、測試、生產環境

version: '3.8'

services:
  # ===== Web 開發環境 =====
  web-dev:
    build:
      context: .
      target: development
    ports:
      - "19006:19006"  # Web 開發服務器
      - "19000:19000"  # Expo DevTools
      - "19001:19001"  # Expo Metro Bundler
      - "19002:19002"  # Expo Tunnel
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_PUBLIC_PLATFORM=web
    env_file:
      - .env
    command: npx expo start --web --host 0.0.0.0
    networks:
      - fintranzo-network

  # ===== Web 生產環境 =====
  web-prod:
    build:
      context: .
      target: web-production
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    volumes:
      - ./docker/ssl:/etc/nginx/ssl:ro
    networks:
      - fintranzo-network

  # ===== iOS 開發環境 =====
  ios-dev:
    build:
      context: .
      target: ios-dev
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_PUBLIC_PLATFORM=ios
    env_file:
      - .env
    command: npx expo start --ios --host 0.0.0.0
    networks:
      - fintranzo-network

  # ===== 測試環境 =====
  test:
    build:
      context: .
      target: testing
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
    env_file:
      - .env.test
    command: npm run test:docker
    networks:
      - fintranzo-network

  # ===== 端到端測試 =====
  e2e-test:
    build:
      context: .
      target: development
    ports:
      - "19007:19006"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - EXPO_PUBLIC_PLATFORM=web
    env_file:
      - .env.test
    command: npm run test:e2e
    depends_on:
      - web-dev
    networks:
      - fintranzo-network

  # ===== 數據庫測試 (可選) =====
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fintranzo_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - fintranzo-network

  # ===== Redis 緩存 (可選) =====
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fintranzo-network

  # ===== 監控服務 =====
  monitoring:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run monitor
    networks:
      - fintranzo-network

volumes:
  postgres_test_data:
  redis_data:

networks:
  fintranzo-network:
    driver: bridge
